### ISSUE TITLE
Migrate repository to findologic

### ISSUE THREAD

**Issue by TheKeymaster** [TheKeymaster/phpdokuwiki2findologic#8]
The repository naming is like "dokuwiki-plugin-*"

* Will follow soon.

**Comment by georgms** [comment]
* Added repository https://github.com/findologic/dokuwiki-plugin-findologic-xml-export, forked from here.
* Granted write access to @TheKeymaster.
* Set up Travis job at https://travis-ci.org/findologic/dokuwiki-plugin-findologic-xml-export.
* Please move the unresolved issues to the new repository. Unfortunately there does not seem to be a way to do this automatically but there be workarounds [migrate GitHub issues](https://github.com/github/hub/issues/886).

**Comment by TheKeymaster** [comment]
@georgms please make sure that it is allowed to create issues. At the moment it is not possible to create issues.

**Comment by georgms** [comment]
@TheKeymaster Done!

**Comment by TheKeymaster** [comment]
This issue was moved to findologic/dokuwiki-plugin-findologic-xml-export#8
